version: 1.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
configuration: Release - With Setup
assembly_info:
  patch: true
  file: 'Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
build:
  project: FeedCenter.sln
  verbosity: minimal
artifacts:
- path: Bootstrapper\bin\Release\FeedCenterSetup.exe
  name: Release
deploy:
- provider: Environment
  name: GitHub
before_build:
- cmd: nuget restore