version: 1.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: x86
assembly_info:
  patch: true
  file: 'Properties\AssemblyInfo.cs'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
before_build:
  - ps: nuget restore .\Installer
  - ps: dotnet publish .\Application\ /p:PublishProfile=Properties\PublishProfiles\x64.pubxml
build:
  project: Installer\Installer.sln
  verbosity: minimal
artifacts:
  - path: Bootstrapper\bin\Release\FeedCenterSetup.exe
    name: Release
for:
  - branches:
      only:
        - main
    deploy:
      - provider: Environment
        name: GitHub
        prerelease: false

  - branches:
      only:
        - prerelease
    version: 1.2.0.{build}
    deploy:
      - provider: Environment
        name: GitHub
        prerelease: true
