version: 1.1.0.{build}
environment:
  DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER: 1
branches:
  only:
    - main
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Previous Visual Studio 2022
configuration: Release
platform: x86  
assembly_info:
  patch: true
  file: 'Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
build:
  project: FeedCenter.sln
  verbosity: normal
artifacts:
- path: Bootstrapper\bin\Release\FeedCenterSetup.exe
  name: Release
deploy:
- provider: Environment
  name: GitHub
before_build:
- cmd: nuget restore