//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public Feed()
        {
            this.Name = "";
            this.Title = "";
            this.Source = "";
            this.Link = "";
            this.Description = "";
            this.LastChecked = new DateTime(599266080000000000, DateTimeKind.Unspecified);
            this.CheckInterval = 60;
            this.Enabled = true;
            this.Authenticate = false;
            this.Username = "";
            this.Password = "";
            this.Domain = "";
            this.LastUpdated = new DateTime(599266080000000000, DateTimeKind.Unspecified);
            this.Actions = new HashSet<FeedAction>();
            this.Items = new HashSet<FeedItem>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Source { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public System.DateTime LastChecked { get; set; }
        public int CheckInterval { get; set; }
        public bool Enabled { get; set; }
        public bool Authenticate { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Domain { get; set; }
        public FeedCenter.FeedReadResult LastReadResult { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public FeedCenter.FeedItemComparison ItemComparison { get; set; }
        public System.Guid CategoryID { get; set; }
        public FeedCenter.MultipleOpenAction MultipleOpenAction { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<FeedAction> Actions { get; set; }
        public virtual ICollection<FeedItem> Items { get; set; }
    }
}
