//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedItem
    {
        public FeedItem()
        {
            this.Title = "";
            this.Link = "";
            this.Description = "";
            this.LastFound = new DateTime(599266080000000000, DateTimeKind.Unspecified);
        }
    
        public System.Guid ID { get; set; }
        public System.Guid FeedID { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public bool BeenRead { get; set; }
        public System.DateTime LastFound { get; set; }
        public bool New { get; set; }
        public string Guid { get; set; }
        public int Sequence { get; set; }
    
        public virtual Feed Feed { get; set; }
    }
}
