//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedAction
    {
        public System.Guid ID { get; set; }
        public System.Guid FeedID { get; set; }
        public int Field { get; set; }
        public string Search { get; set; }
        public string Replace { get; set; }
        public int Sequence { get; set; }
    
        public virtual Feed Feed { get; set; }
    }
}
