//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeedCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_ctions.
        /// </summary>
        public static string ActionsButton {
            get {
                return ResourceManager.GetString("ActionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategoryButton {
            get {
                return ResourceManager.GetString("AddCategoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feed.
        /// </summary>
        public static string AddFeedButton {
            get {
                return ResourceManager.GetString("AddFeedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddLink {
            get {
                return ResourceManager.GetString("AddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; all &gt;.
        /// </summary>
        public static string AllCategory {
            get {
                return ResourceManager.GetString("AllCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Center.
        /// </summary>
        public static string ApplicationDisplayName {
            get {
                return ResourceManager.GetString("ApplicationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedCenter.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string authenticationPasswordLabel {
            get {
                return ResourceManager.GetString("authenticationPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string authenticationTab {
            get {
                return ResourceManager.GetString("authenticationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string authenticationUserNameLabel {
            get {
                return ResourceManager.GetString("authenticationUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Multiple Feeds.
        /// </summary>
        public static string BulkFeedWindow {
            get {
                return ResourceManager.GetString("BulkFeedWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        public static string CategoriesHeader {
            get {
                return ResourceManager.GetString("CategoriesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: {0}.
        /// </summary>
        public static string CategoryFilterHeader {
            get {
                return ResourceManager.GetString("CategoryFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryNameColumnHeader {
            get {
                return ResourceManager.GetString("CategoryNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string categoryNameLabel {
            get {
                return ResourceManager.GetString("categoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string CategoryWindowAdd {
            get {
                return ResourceManager.GetString("CategoryWindowAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string CategoryWindowEdit {
            get {
                return ResourceManager.GetString("CategoryWindowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check _Now.
        /// </summary>
        public static string checkVersionNowButton {
            get {
                return ResourceManager.GetString("checkVersionNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check for a new version on startup.
        /// </summary>
        public static string checkVersionOnStartupCheckBox {
            get {
                return ResourceManager.GetString("checkVersionOnStartupCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this category?
        ///
        ///All feeds currently in category &quot;{0}&quot; will be moved to the default category..
        /// </summary>
        public static string ConfirmDeleteCategory {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this feed?.
        /// </summary>
        public static string ConfirmDeleteFeed {
            get {
                return ResourceManager.GetString("ConfirmDeleteFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected feeds?.
        /// </summary>
        public static string ConfirmDeleteFeeds {
            get {
                return ResourceManager.GetString("ConfirmDeleteFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Category
        ///(
        ///	ID					uniqueidentifier	NOT NULL,
        ///	Name				nvarchar(1000)		NOT NULL		DEFAULT &apos;&apos;,
        ///
        ///	CONSTRAINT PK_Category PRIMARY KEY (ID)
        ///)
        ///GO
        ///
        ///CREATE TABLE Setting
        ///(
        ///	Name				nvarchar(500)		NOT NULL		DEFAULT &apos;&apos;,
        ///	Value				nvarchar(3500)		NOT NULL		DEFAULT &apos;&apos;,
        ///	Version				nvarchar(50)		NOT NULL		DEFAULT &apos;&apos;,
        ///
        ///	CONSTRAINT PK_Setting PRIMARY KEY (Name, Version)
        ///)
        ///GO
        ///
        ///CREATE TABLE Feed
        ///(
        ///	ID					uniqueidentifier	NOT NULL,
        ///	Name				nvarchar(1000)		NOT NULL		DEFAULT &apos;&apos;,
        ///	Title				 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Feed.
        /// </summary>
        public static string CurrentFeed {
            get {
                return ResourceManager.GetString("CurrentFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE FeedItem ADD COLUMN Guid nvarchar(1000)
        ///GO
        ///
        ///UPDATE	FeedItem
        ///SET		Guid = &apos;&apos;
        ///WHERE	Guid IS NULL
        ///GO
        ///
        ///ALTER TABLE FeedItem ALTER COLUMN Guid nvarchar(1000) NOT NULL
        ///GO
        ///
        ///ALTER TABLE FeedItem ALTER COLUMN Guid SET DEFAULT &apos;&apos;
        ///GO
        ///
        ///UPDATE	Setting
        ///SET		Value = &apos;2&apos;
        ///WHERE	Name = &apos;DatabaseVersion&apos;
        ///GO
        ///.
        /// </summary>
        public static string DatabaseUpdate_1 {
            get {
                return ResourceManager.GetString("DatabaseUpdate_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE		FeedItem 
        ///ALTER COLUMN	Description 
        ///DROP DEFAULT
        ///GO
        ///
        ///ALTER TABLE		FeedItem
        ///ALTER COLUMN	Description ntext NOT NULL 
        ///GO
        ///
        ///ALTER TABLE		FeedItem
        ///ALTER COLUMN	Description SET DEFAULT &apos;&apos; 
        ///GO
        ///
        ///ALTER TABLE		FeedItem 
        ///ALTER COLUMN	Title 
        ///DROP DEFAULT
        ///GO
        ///
        ///ALTER TABLE		FeedItem
        ///ALTER COLUMN	Title ntext NOT NULL 
        ///GO
        ///
        ///ALTER TABLE		FeedItem
        ///ALTER COLUMN	Title SET DEFAULT &apos;&apos; 
        ///GO
        ///
        ///UPDATE	Setting
        ///SET		Value = &apos;3&apos;
        ///WHERE	Name = &apos;DatabaseVersion&apos;
        ///GO
        ///.
        /// </summary>
        public static string DatabaseUpdate_2 {
            get {
                return ResourceManager.GetString("DatabaseUpdate_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE	Category
        ///SET		Name = &apos;&lt; default &gt;&apos;
        ///WHERE	Name = &apos;Default&apos;
        ///GO
        ///
        ///UPDATE	Setting
        ///SET		Value = &apos;4&apos;
        ///WHERE	Name = &apos;DatabaseVersion&apos;
        ///GO
        ///.
        /// </summary>
        public static string DatabaseUpdate_3 {
            get {
                return ResourceManager.GetString("DatabaseUpdate_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE		Feed
        ///DROP COLUMN		Sequence
        ///GO
        ///
        ///UPDATE	Setting
        ///SET		Value = &apos;5&apos;
        ///WHERE	Name = &apos;DatabaseVersion&apos;
        ///GO
        ///.
        /// </summary>
        public static string DatabaseUpdate_4 {
            get {
                return ResourceManager.GetString("DatabaseUpdate_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE Feed ADD COLUMN MultipleOpenAction int
        ///GO
        ///
        ///UPDATE	Feed
        ///SET		MultipleOpenAction = 0
        ///WHERE	MultipleOpenAction IS NULL
        ///GO
        ///
        ///ALTER TABLE Feed ALTER COLUMN MultipleOpenAction int NOT NULL
        ///GO
        ///
        ///ALTER TABLE Feed ALTER COLUMN MultipleOpenAction SET DEFAULT 0
        ///GO
        ///
        ///UPDATE	Setting
        ///SET		Value = &apos;6&apos;
        ///WHERE	Name = &apos;DatabaseVersion&apos;
        ///GO
        ///.
        /// </summary>
        public static string DatabaseUpdate_5 {
            get {
                return ResourceManager.GetString("DatabaseUpdate_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE DatabaseVersion
        ///(
        ///	Value				int		NOT NULL		DEFAULT 0
        ///)
        ///GO
        ///
        ///INSERT	DatabaseVersion
        ///		(Value)
        ///VALUES	(7)
        ///GO
        ///
        ///DELETE	Setting
        ///WHERE	Name = &apos;DatabaseVersion&apos;
        ///GO
        ///.
        /// </summary>
        public static string DatabaseUpdate_6 {
            get {
                return ResourceManager.GetString("DatabaseUpdate_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Windows Default &gt;.
        /// </summary>
        public static string DefaultBrowserCaption {
            get {
                return ResourceManager.GetString("DefaultBrowserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default browser.
        /// </summary>
        public static string defaultBrowserLabel {
            get {
                return ResourceManager.GetString("defaultBrowserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Center.
        /// </summary>
        public static string DefaultUserAgentCaption {
            get {
                return ResourceManager.GetString("DefaultUserAgentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user agent.
        /// </summary>
        public static string defaultUserAgentLabel {
            get {
                return ResourceManager.GetString("defaultUserAgentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string DeleteCategoryButton {
            get {
                return ResourceManager.GetString("DeleteCategoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Feed.
        /// </summary>
        public static string DeleteFeedButton {
            get {
                return ResourceManager.GetString("DeleteFeedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLink {
            get {
                return ResourceManager.GetString("DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to disable.
        /// </summary>
        public static string DisableHint {
            get {
                return ResourceManager.GetString("DisableHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Display empty feeds.
        /// </summary>
        public static string displayEmptyFeedsCheckBox {
            get {
                return ResourceManager.GetString("displayEmptyFeedsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string EditCategoryButton {
            get {
                return ResourceManager.GetString("EditCategoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Feed.
        /// </summary>
        public static string EditFeedButton {
            get {
                return ResourceManager.GetString("EditFeedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLink {
            get {
                return ResourceManager.GetString("EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to enable.
        /// </summary>
        public static string EnableHint {
            get {
                return ResourceManager.GetString("EnableHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Feeds.
        /// </summary>
        public static string ExportFeedsButton {
            get {
                return ResourceManager.GetString("ExportFeedsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportLink {
            get {
                return ResourceManager.GetString("ExportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In field &apos;{0}&apos; - search for &apos;{1}&apos; - replace with &apos;{2}&apos;.
        /// </summary>
        public static string FeedActionDescription {
            get {
                return ResourceManager.GetString("FeedActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been successfully added to your feed list..
        /// </summary>
        public static string FeedAddedNotification {
            get {
                return ResourceManager.GetString("FeedAddedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication user name must be specified.
        /// </summary>
        public static string FeedAuthenticationUserNameError {
            get {
                return ResourceManager.GetString("FeedAuthenticationUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string feedCategoryLabel {
            get {
                return ResourceManager.GetString("feedCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Feed to Add.
        /// </summary>
        public static string FeedChooserWindow {
            get {
                return ResourceManager.GetString("FeedChooserWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string FeedErrorColumnHeader {
            get {
                return ResourceManager.GetString("FeedErrorColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One feed has an error.
        /// </summary>
        public static string FeedErrorLink {
            get {
                return ResourceManager.GetString("FeedErrorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feeds have errors.
        /// </summary>
        public static string FeedErrorsLink {
            get {
                return ResourceManager.GetString("FeedErrorsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Reading Errors.
        /// </summary>
        public static string FeedErrorWindow {
            get {
                return ResourceManager.GetString("FeedErrorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed link contains.
        /// </summary>
        public static string FeedLinkFilterLabel {
            get {
                return ResourceManager.GetString("FeedLinkFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string FeedNameColumnHeader {
            get {
                return ResourceManager.GetString("FeedNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed name must be specified.
        /// </summary>
        public static string FeedNameError {
            get {
                return ResourceManager.GetString("FeedNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string feedNameLabel {
            get {
                return ResourceManager.GetString("feedNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh feed every.
        /// </summary>
        public static string feedReadIntervalPrefix {
            get {
                return ResourceManager.GetString("feedReadIntervalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string feedReadIntervalSuffix {
            get {
                return ResourceManager.GetString("feedReadIntervalSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string FeedReadResult_ConnectionFailed {
            get {
                return ResourceManager.GetString("FeedReadResult_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string FeedReadResult_InvalidXml {
            get {
                return ResourceManager.GetString("FeedReadResult_InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response.
        /// </summary>
        public static string FeedReadResult_NoResponse {
            get {
                return ResourceManager.GetString("FeedReadResult_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string FeedReadResult_NotFound {
            get {
                return ResourceManager.GetString("FeedReadResult_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string FeedReadResult_ServerError {
            get {
                return ResourceManager.GetString("FeedReadResult_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string FeedReadResult_Timeout {
            get {
                return ResourceManager.GetString("FeedReadResult_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        public static string FeedReadResult_Unauthorized {
            get {
                return ResourceManager.GetString("FeedReadResult_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds:.
        /// </summary>
        public static string FeedsHeader {
            get {
                return ResourceManager.GetString("FeedsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed URL must be specified.
        /// </summary>
        public static string FeedUrlError {
            get {
                return ResourceManager.GetString("FeedUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string feedUrlLabel {
            get {
                return ResourceManager.GetString("feedUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feed.
        /// </summary>
        public static string FeedWindowAdd {
            get {
                return ResourceManager.GetString("FeedWindowAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Feed.
        /// </summary>
        public static string FeedWindowEdit {
            get {
                return ResourceManager.GetString("FeedWindowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string generalTab {
            get {
                return ResourceManager.GetString("generalTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPML Files (*.opml)|*.opml|All Files (*.*)|*.*.
        /// </summary>
        public static string ImportExportFilter {
            get {
                return ResourceManager.GetString("ImportExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Feeds.
        /// </summary>
        public static string ImportFeedsButton {
            get {
                return ResourceManager.GetString("ImportFeedsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportLink {
            get {
                return ResourceManager.GetString("ImportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdatedColumnHeader {
            get {
                return ResourceManager.GetString("LastUpdatedColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lock window.
        /// </summary>
        public static string lockWindowCheckBox {
            get {
                return ResourceManager.GetString("lockWindowCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark feed as read.
        /// </summary>
        public static string markReadToolbarButton {
            get {
                return ResourceManager.GetString("markReadToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Multiple Feeds.
        /// </summary>
        public static string MultipleEditButton {
            get {
                return ResourceManager.GetString("MultipleEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Edit.
        /// </summary>
        public static string MultipleEditLink {
            get {
                return ResourceManager.GetString("MultipleEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only first line.
        /// </summary>
        public static string multipleLineDisplayFirstLine {
            get {
                return ResourceManager.GetString("multipleLineDisplayFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline titles.
        /// </summary>
        public static string multipleLineDisplayLabel {
            get {
                return ResourceManager.GetString("multipleLineDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave alone.
        /// </summary>
        public static string multipleLineDisplayNormal {
            get {
                return ResourceManager.GetString("multipleLineDisplayNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten to single line.
        /// </summary>
        public static string multipleLineDisplaySingleLine {
            get {
                return ResourceManager.GetString("multipleLineDisplaySingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string NewVersionLink {
            get {
                return ResourceManager.GetString("NewVersionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next feed.
        /// </summary>
        public static string nextToolbarButton {
            get {
                return ResourceManager.GetString("nextToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string NotificationIconContextMenuExit {
            get {
                return ResourceManager.GetString("NotificationIconContextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock window.
        /// </summary>
        public static string NotificationIconContextMenuLocked {
            get {
                return ResourceManager.GetString("NotificationIconContextMenuLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; no title &gt;.
        /// </summary>
        public static string NoTitleText {
            get {
                return ResourceManager.GetString("NoTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkayButton {
            get {
                return ResourceManager.GetString("OkayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all links on individual pages.
        /// </summary>
        public static string openAllMultipleToolbarButton {
            get {
                return ResourceManager.GetString("openAllMultipleToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all links on single page.
        /// </summary>
        public static string openAllSingleToolbarButton {
            get {
                return ResourceManager.GetString("openAllSingleToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Feed.
        /// </summary>
        public static string OpenFeed {
            get {
                return ResourceManager.GetString("OpenFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Open all&quot; action.
        /// </summary>
        public static string openLabel {
            get {
                return ResourceManager.GetString("openLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Page.
        /// </summary>
        public static string OpenPage {
            get {
                return ResourceManager.GetString("OpenPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string optionCategoryAbout {
            get {
                return ResourceManager.GetString("optionCategoryAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string optionCategoryCategories {
            get {
                return ResourceManager.GetString("optionCategoryCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string optionCategoryDisplay {
            get {
                return ResourceManager.GetString("optionCategoryDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        public static string optionCategoryFeeds {
            get {
                return ResourceManager.GetString("optionCategoryFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string optionCategoryGeneral {
            get {
                return ResourceManager.GetString("optionCategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string optionCategoryReading {
            get {
                return ResourceManager.GetString("optionCategoryReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string optionCategoryUpdate {
            get {
                return ResourceManager.GetString("optionCategoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string optionsToolbarButton {
            get {
                return ResourceManager.GetString("optionsToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsWindow {
            get {
                return ResourceManager.GetString("OptionsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous feed.
        /// </summary>
        public static string previousToolbarButton {
            get {
                return ResourceManager.GetString("previousToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string readingTab {
            get {
                return ResourceManager.GetString("readingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all feeds.
        /// </summary>
        public static string refreshAllToolbarButton {
            get {
                return ResourceManager.GetString("refreshAllToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RefreshCurrent {
            get {
                return ResourceManager.GetString("RefreshCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh current feed.
        /// </summary>
        public static string refreshToolbarButton {
            get {
                return ResourceManager.GetString("refreshToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Register as default feed reader.
        /// </summary>
        public static string registerAsDefaultFeedReaderCheckBox {
            get {
                return ResourceManager.GetString("registerAsDefaultFeedReaderCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Feed requires authentication.
        /// </summary>
        public static string requiresAuthenticationCheckBox {
            get {
                return ResourceManager.GetString("requiresAuthenticationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string SelectAllLabel {
            get {
                return ResourceManager.GetString("SelectAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string SelectInvertLabel {
            get {
                return ResourceManager.GetString("SelectInvertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select:.
        /// </summary>
        public static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SelectNoneLabel {
            get {
                return ResourceManager.GetString("SelectNoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show problems from last refresh.
        /// </summary>
        public static string showErrorsToolbarButton {
            get {
                return ResourceManager.GetString("showErrorsToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all items on a single page.
        /// </summary>
        public static string showOnSinglePageToolbarButton {
            get {
                return ResourceManager.GetString("showOnSinglePageToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string SortFeeds {
            get {
                return ResourceManager.GetString("SortFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for legacy database....
        /// </summary>
        public static string SplashCheckingForLegacyDatabase {
            get {
                return ResourceManager.GetString("SplashCheckingForLegacyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for update....
        /// </summary>
        public static string SplashCheckingForUpdate {
            get {
                return ResourceManager.GetString("SplashCheckingForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database....
        /// </summary>
        public static string SplashCreatingDatabase {
            get {
                return ResourceManager.GetString("SplashCreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        public static string SplashDownloadingUpdate {
            get {
                return ResourceManager.GetString("SplashDownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing update....
        /// </summary>
        public static string SplashInstallingUpdate {
            get {
                return ResourceManager.GetString("SplashInstallingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading database....
        /// </summary>
        public static string SplashLoadingDatabase {
            get {
                return ResourceManager.GetString("SplashLoadingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintaining legacy database....
        /// </summary>
        public static string SplashMaintainingLegacyDatabase {
            get {
                return ResourceManager.GetString("SplashMaintainingLegacyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating legacy database....
        /// </summary>
        public static string SplashMigratingLegacyDatabase {
            get {
                return ResourceManager.GetString("SplashMigratingLegacyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting....
        /// </summary>
        public static string SplashRestarting {
            get {
                return ResourceManager.GetString("SplashRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string SplashStarting {
            get {
                return ResourceManager.GetString("SplashStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating legacy database....
        /// </summary>
        public static string SplashUpdatingLegacyDatabase {
            get {
                return ResourceManager.GetString("SplashUpdatingLegacyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start when Windows starts.
        /// </summary>
        public static string startWithWindowsCheckBox {
            get {
                return ResourceManager.GetString("startWithWindowsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar location.
        /// </summary>
        public static string toolbarLocationLabel {
            get {
                return ResourceManager.GetString("toolbarLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
